.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. yatripay_qt test_yatripay_qt
clean: FORCE
	$(MAKE) -C .. yatripay_qt_clean test_yatripay_qt_clean
check: FORCE
	$(MAKE) -C .. test_yatripay_qt_check
yatripay-qt yatripay-qt.exe: FORCE
	 $(MAKE) -C .. yatripay_qt
